spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/foodie-shop?characterEncoding=utf8&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 1234
  redis:
    host: 47.113.206.216
    port: 6379
    password: nathanchenredis
    database: 2
    pool:
      # 链接池中最大空闲的连接数,默认为8
      max-idle: 10
      # 当连接池资源耗尽时，等待时间，超出则抛异常，默认为-1即永不超时
      max-wait: 30000
      # 链接池中最大的连接数,默认为8
      max-active: 10
#security:
#  oauth2:
#    client:
#      client-id: seehope
#      client-secret: 123456
mybatis:
  mapper-locations:
    - classpath*:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
logging:
  level:
    org.springframework: info
    net.seehope: debug
net:
    browser:
      swagger: /swagger-ui/*